highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyllt.github.io/vitae
author: Gwanho Kim

# edit this section with your information
# jekyllt.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Gwanho Kim's Resume
name: Gwanho Kim
contact: khkim6040@gmail.com
blog: https://blog.naver.com/ho0ou
github: https://github.com/khkim6040
soundcloud: https://soundcloud.com/ho0ou
solvedac: https://solved.ac/profile/khkim6040
google_maps: 'https://www.postech.ac.kr/eng/'
address:
  city: POSTECH
  country: South Korea
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
